<a href="https://colab.research.google.com/github/albim72/__DEEP_03/blob/main/basics_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
nb = [45,6,18,0,-5,78,123,48,90,2,13,177,800,-99,-2,-14,555]

In [4]:
nnb = np.array(nb)
nnb

array([ 45,   6,  18,   0,  -5,  78, 123,  48,  90,   2,  13, 177, 800,
       -99,  -2, -14, 555])

In [5]:
nb.sort()
nb

[-99, -14, -5, -2, 0, 2, 6, 13, 18, 45, 48, 78, 90, 123, 177, 555, 800]

In [6]:
nnb.sort()
nnb

array([-99, -14,  -5,  -2,   0,   2,   6,  13,  18,  45,  48,  78,  90,
       123, 177, 555, 800])

In [7]:
s = [1,6,89,4]
d = [23,8,1,67]
g = [8,24,56,15]

full = s+d+g
full

[1, 6, 89, 4, 23, 8, 1, 67, 8, 24, 56, 15]

In [9]:
snp = np.array(s)
dnp = np.array(d)
gnp = np.array(g)
npsum = snp+dnp+gnp
npsum

array([ 32,  38, 146,  86])

In [11]:
npfull = np.concatenate((snp,dnp,gnp))
npfull

array([ 1,  6, 89,  4, 23,  8,  1, 67,  8, 24, 56, 15])

In [12]:
zx = [[6,8],[33,9]]
zx

[[6, 8], [33, 9]]

In [15]:
zx[1][0]

33

In [20]:
x = np.array([[99,3],[19,6]])
y = np.array([[100,66],[66,100]])
x,y

(array([[99,  3],
        [19,  6]]), array([[100,  66],
        [ 66, 100]]))

In [21]:
x[0,1]

3

In [22]:
x[0][1]

3

In [25]:
p = np.concatenate((x,y),axis=0)
p

array([[ 99,   3],
       [ 19,   6],
       [100,  66],
       [ 66, 100]])

In [26]:
prosta = np.arange(12)
prosta

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
pp = prosta.reshape(3,4)
pp

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
pp.shape

(3, 4)