In [1]:
import numpy as np

In [3]:
w = np.array([[1,2,3,4],[16,18,19,22],[99,101,121,555]])
w

array([[ 1, 2, 3, 4],
 [ 16, 18, 19, 22],
 [ 99, 101, 121, 555]])

In [4]:
print(w[w<19])

[ 1  2  3  4 16 18]


In [6]:
pc = (w>=19)
print(w[pc])

[ 19  22  99 101 121 555]


In [7]:
pv = (w%2==0)
print(w[pv])

[ 2  4 16 18 22]


<h2 style="color:red;">Operacje na macierzach</h2>
<img src="matrix.png">
<p>
<ul>
<li>dodawanie</li>
<li>odejmowanie</li>
<li>mnożenie</li>
<li>dzielenie</li>
</ul>
</p>

In [8]:
dane_one = np.array([1,6,9])
dane_two = np.array([2,2,3])
ones = np.ones(3,dtype=int)

In [9]:
print(dane_one+ones)

[ 2  7 10]


In [10]:
print(dane_one-ones)

[0 5 8]


In [11]:
print(dane_one*dane_two)

[ 2 12 27]


In [12]:
print(dane_one/dane_two)

[0.5 3.  3. ]


In [13]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [14]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [15]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [16]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [17]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[13,17,89],[45,8,90]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 17, 89],
        [45,  8, 90]]])

In [18]:
arr3D[0]

array([[1, 2, 3],
 [4, 5, 6]])

In [19]:
old_values = arr3D[0].copy()
arr3D[0] = 55
arr3D

array([[[55, 55, 55],
        [55, 55, 55]],

       [[13, 17, 89],
        [45,  8, 90]]])

In [20]:
arr3D[0] = old_values
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 17, 89],
        [45,  8, 90]]])